package org.smartdox.generators

import java.io._
import java.net._
import java.nio.charset.StandardCharsets
import org.goldenport.context.Consequence
import org.goldenport.io.IoUtils
import org.smartdox.generator.Context
import scala.util.control.NonFatal

/*
 * Kroki diagram generator with cache integration.
 *
 * Generates diagrams via Kroki API (https://kroki.io) and stores them
 * in a local cache using KrokiCache.
 *
 * @since   Oct. 12, 2025
 * @version Oct. 15, 2025
 * @author  ASAMI
 */
class KrokiGenerator(
  context: Context,
  cache: KrokiCache,
  krokiServerUrl: String = "http://localhost:9609", // "https://kroki.io",
  defaultFormat: String = "svg"
) {

  //
  // Public API
  //

  /**
   * Generates (or retrieves cached) diagram from Kroki.
   *
   * @param language Diagram language (e.g. "plantuml", "mermaid")
   * @param source   Diagram definition text
   * @param format   Output format ("svg", "png", "pdf"), default "svg"
   * @return Cached or newly generated diagram file
   */
  def generate(
    language: String,
    source: String,
    format: String = defaultFormat
  ): Consequence[File] = Consequence {
    // 1. Try to load from cache
    cache.get(Some(language), source, format) match {
      case Some(file) =>
        context.log.debug(s"Use cached Kroki diagram: ${file.getPath}")
        file

      case None =>
        context.log.info(s"Generating new Kroki diagram: $language / $format")
        val bytes = _fetch_from_kroki(language, source, format)
        cache.set(Some(language), source, format, bytes)
        cache.get(Some(language), source, format).getOrElse {
          throw new IllegalStateException(s"Cache write failed for $language diagram")
        }
    }
  }

  /**
   * Generates (or retrieves cached) diagram as an SVG string.
   * Suitable for inline HTML embedding.
   */
  def generateSvgString(language: String, source: String): Consequence[String] = Consequence {
    // 1. Try to load from cache
    cache.load(Some(language), source, "svg") match {
      case Some(bytes) =>
        context.log.debug(s"Use cached SVG for language: $language")
        new String(bytes, StandardCharsets.UTF_8)

      case None =>
        context.log.info(s"Generating SVG via Kroki: $language")
        val bytes = _fetch_from_kroki(language, source, "svg")
        cache.set(Some(language), source, "svg", bytes)
        new String(bytes, StandardCharsets.UTF_8)
    }
  }

  //
  // Internal
  //

  /**
   * Calls Kroki API and returns generated bytes.
   */
  private def _fetch_from_kroki(language: String, source: String, format: String): Array[Byte] = {
    val endpoint = s"$krokiServerUrl/$language/$format"
    val url = new URI(endpoint).toURL
    val conn = url.openConnection().asInstanceOf[HttpURLConnection]
    conn.setDoOutput(true)
    conn.setRequestMethod("POST")
    conn.setRequestProperty("Content-Type", "text/plain; charset=UTF-8")

    // 送信
    val out = new OutputStreamWriter(conn.getOutputStream, StandardCharsets.UTF_8)
    out.write(source)
    out.flush()
    out.close()

    // 応答取得
    val in = new BufferedInputStream(conn.getInputStream)
    val bytes = Stream.continually(in.read).takeWhile(_ != -1).map(_.toByte).toArray
    in.close()

    if (conn.getResponseCode != 200)
      throw new RuntimeException(s"Kroki request failed: ${conn.getResponseCode}")

    bytes
  }
}

object KrokiGenerator {
  /**
   * Creates a KrokiGenerator with default cache configuration.
   */
  def apply(context: Context): KrokiGenerator = {
    val cache = KrokiCache(context)
    new KrokiGenerator(context, cache)
  }

  /**
   * Creates a KrokiGenerator with custom cache directory.
   */
  def apply(context: Context, cacheDir: File, useLanguageSubdir: Boolean): KrokiGenerator = {
    val cache = KrokiCache(cacheDir, useLanguageSubdir, context)
    new KrokiGenerator(context, cache)
  }
}
