package org.smartdox.generators

import java.io._
import java.net._
import java.nio.charset.StandardCharsets
import org.goldenport.context.Consequence
import org.smartdox.generator.Context

/*
 * Kroki diagram generator with cache integration.
 *
 * Generates diagrams via Kroki and stores them in a local cache using
 * KrokiCache. A configured Kroki server is used when available; otherwise
 * the bundled SmartDox dependency Docker image is used as a one-shot command.
 *
 * @since   Oct. 12, 2025
 *  version Oct. 15, 2025
 * @version Jun. 21, 2026
 * @author  ASAMI
 */
class KrokiGenerator(
  context: Context,
  cache: KrokiCache,
  krokiServerUrl: Option[String] = KrokiGenerator.defaultServerUrl,
  defaultFormat: String = "svg",
  dockerImage: String = KrokiGenerator.defaultDockerImage,
  dockerCommand: String = KrokiGenerator.defaultDockerCommand
) {
  def this(
    context: Context,
    cache: KrokiCache,
    krokiServerUrl: String,
    defaultFormat: String
  ) = this(context, cache, Option(krokiServerUrl).filter(_.trim.nonEmpty), defaultFormat)

  //
  // Public API
  //

  /**
   * Generates (or retrieves cached) diagram from Kroki.
   *
   * @param language Diagram language (e.g. "plantuml", "mermaid")
   * @param source   Diagram definition text
   * @param format   Output format ("svg", "png", "pdf"), default "svg"
   * @return Cached or newly generated diagram file
   */
  def generate(
    language: String,
    source: String,
    format: String = defaultFormat
  ): Consequence[File] = Consequence {
    // 1. Try to load from cache
    cache.get(Some(language), source, format) match {
      case Some(file) =>
        context.log.debug(s"Use cached Kroki diagram: ${file.getPath}")
        file

      case None =>
        context.log.info(s"Generating new Kroki diagram: $language / $format")
        val bytes = _fetch_from_kroki(language, source, format)
        cache.set(Some(language), source, format, bytes)
        cache.get(Some(language), source, format).getOrElse {
          throw new IllegalStateException(s"Cache write failed for $language diagram")
        }
    }
  }

  /**
   * Generates (or retrieves cached) diagram as an SVG string.
   * Suitable for inline HTML embedding.
   */
  def generateSvgString(language: String, source: String): Consequence[String] = Consequence {
    // 1. Try to load from cache
    cache.load(Some(language), source, "svg") match {
      case Some(bytes) =>
        context.log.debug(s"Use cached SVG for language: $language")
        new String(bytes, StandardCharsets.UTF_8)

      case None =>
        context.log.info(s"Generating SVG via Kroki: $language")
        val bytes = _fetch_from_kroki(language, source, "svg")
        cache.set(Some(language), source, "svg", bytes)
        new String(bytes, StandardCharsets.UTF_8)
    }
  }

  //
  // Internal
  //

  /**
   * Calls Kroki API and returns generated bytes.
   */
  private def _fetch_from_kroki(language: String, source: String, format: String): Array[Byte] =
    krokiServerUrl match {
      case Some(url) => _fetch_from_kroki_server(url, language, source, format)
      case None => _fetch_from_kroki_docker(language, source, format)
    }

  private def _fetch_from_kroki_server(
    serverUrl: String,
    language: String,
    source: String,
    format: String
  ): Array[Byte] = {
    val krokiServerUrl = serverUrl.stripSuffix("/")
    val endpoint = s"$krokiServerUrl/$language/$format"
    val url = new URI(endpoint).toURL
    val conn = url.openConnection().asInstanceOf[HttpURLConnection]
    conn.setDoOutput(true)
    conn.setRequestMethod("POST")
    conn.setRequestProperty("Content-Type", "text/plain; charset=UTF-8")

    // 送信
    val out = new OutputStreamWriter(conn.getOutputStream, StandardCharsets.UTF_8)
    out.write(source)
    out.flush()
    out.close()

    // 応答取得
    val in = new BufferedInputStream(conn.getInputStream)
    val bytes = Stream.continually(in.read).takeWhile(_ != -1).map(_.toByte).toArray
    in.close()

    if (conn.getResponseCode != 200)
      throw new RuntimeException(s"Kroki request failed: ${conn.getResponseCode}")

    bytes
  }

  private def _fetch_from_kroki_docker(
    language: String,
    source: String,
    format: String
  ): Array[Byte] = {
    val pb = new ProcessBuilder(
      dockerCommand,
      "run",
      "--rm",
      "-i",
      dockerImage,
      "kroki-render",
      language,
      format
    )
    val process = pb.start()
    val out = new OutputStreamWriter(process.getOutputStream, StandardCharsets.UTF_8)
    out.write(source)
    out.flush()
    out.close()
    val bytes = _read_all(process.getInputStream)
    val errors = _read_all(process.getErrorStream)
    val exitCode = process.waitFor()
    if (exitCode == 0)
      bytes
    else {
      val message = new String(errors, StandardCharsets.UTF_8).trim
      throw new RuntimeException(s"Kroki Docker request failed: $message")
    }
  }

  private def _read_all(in: InputStream): Array[Byte] = {
    val out = new ByteArrayOutputStream()
    val buffer = new Array[Byte](8192)
    var n = in.read(buffer)
    while (n != -1) {
      out.write(buffer, 0, n)
      n = in.read(buffer)
    }
    in.close()
    out.toByteArray
  }
}

object KrokiGenerator {
  private[generators] val _default_direct_docker_image = "simplemodeling/smartdox-pdf:latest"

  def defaultServerUrl: Option[String] =
    _sysprop("smartdox.kroki.server.url")
      .orElse(_env("SMARTDOX_KROKI_SERVER_URL"))
      .orElse(_env("KROKI_SERVER_URL"))

  def defaultDockerImage: String =
    _sysprop("smartdox.kroki.docker.image")
      .orElse(_env("SMARTDOX_KROKI_DOCKER_IMAGE"))
      .orElse(_env("SMARTDOX_COZY_TOOLCHAIN_IMAGE"))
      .orElse(_env("SMARTDOX_PDF_DOCKER_IMAGE"))
      .getOrElse(_default_direct_docker_image)

  def defaultDockerCommand: String =
    _sysprop("smartdox.docker.command")
      .orElse(_env("SMARTDOX_DOCKER"))
      .getOrElse("docker")

  private def _sysprop(name: String): Option[String] =
    Option(System.getProperty(name)).map(_.trim).filter(_.nonEmpty)

  private def _env(name: String): Option[String] =
    Option(System.getenv(name)).map(_.trim).filter(_.nonEmpty)

  /**
   * Creates a KrokiGenerator with default cache configuration.
   */
  def apply(context: Context): KrokiGenerator = {
    val cache = KrokiCache(context)
    new KrokiGenerator(context, cache)
  }

  /**
   * Creates a KrokiGenerator with custom cache directory.
   */
  def apply(context: Context, cacheDir: File, useLanguageSubdir: Boolean): KrokiGenerator = {
    val cache = KrokiCache(cacheDir, useLanguageSubdir, context)
    new KrokiGenerator(context, cache)
  }
}
